/*FORMAS NORMAIS SÃO DIRETRIZES PARA APLICAR EM MODELAGEM DE AMBIENTES OLTP OU AMBIENTES TRANSACIONAIS DE BD
HOJE TEMOS + DE 3 FORMAS NORMAIS. MAS COM SOMENTE TRÊS É O SUFICIENTE PARA TER UM CÓDIGO LIMPO
*/

INSERT INTO CLIENTE VALUES('JOAQUIM', 'M', 'J.QUIM@OUTLOOK.COM', 12312312, '45853692 - 12312312', 'RUA COPPERFIELD - WILLIANSBURG - KITCHENER');

UPDATE CLIENTE SET TELEFONE = '45853692 - 12312312' WHERE NOME = 'JOAQUIM' ;

SELECT SEXO, COUNT(*) AS QTD FROM CLIENTE GROUP BY SEXO;

/* PRIMEIRA FORMA NORMAL 

REGRA 1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA
[AMARELO, AZUL, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS
EX.: TELEFONE DO CLIENTE JOQUIM

REGRA 2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA
QUANDO O CAMPO FOR DIVISIVEL 
EX.: O CAMPO DE ENDEREÇO DA TABELA DE CLIENTE

REGRA 3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE INDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO.
ISSO É O QUE CHAMAMOS DE PRIMARY KEY(PK). 


*/

