/* SCRIPT 1 */

/* selecionando o banco de dados*/
use projeto;
/* exibindo as tabelas */
show tables;
/* exibindo a estrutura de uma tabela */
desc cliente;

CREATE DATABASE PROJETO;

CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENEDERECO VARCHAR(100)
);

/* FORMA 01 - OMITINDO AS COLUNAS */
INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@HOTMAIL.COM',123123123,'12345678998','JARDIM DAS CEREJEIRAS - BAIRRO X - CIDADE Y');
INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');
INSERT INTO CLIENTE VALUES('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
/*FORMA 02 - COLOCANDO AS COLUNAS (A ORDEM PODE SER ALEATÓRIA CONFORME ESPECIFICADO NA TABLE)*/
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES(
'ANA', 'F', 'ANA@OUTLOOK.COM', 123123123, '12312312345', 'ENDEREÇO DA RUA OU LOGRADOURO - BAIRRO - CIDADE');  
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES(
'LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* O COMANDO SELECT - PROJEÇAO*/

SELECT NOW() AS DATA_HORA;

SELECT 'JOÃO DA SILVA';

SELECT 'BANCO DE DADOS';
SELECT NOW() AS DATA_HORA, 'ALEXANDRE SABBAG' AS ALUNO;

/* ALIAS DE COLUNA */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

/* FILTRANDO OS DADOS COM WHERE E LIKE */

SELECT NOME , SEXO FROM CLIENTE WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE 'Y';/* ERRO */

/* CARACTER CORINGA % -> ANTES OU DEPOIS DA SELECAO, QUALQUER COISA*/
SELECT NOME, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%Y';